### ISSUE TITLE
案例2

### ISSUE THREAD

**Issue by rocky-luo** [aneasystone/mysql-deadlocks#1]
即使是事务2和事务3进行一次当前读，但是在RC级别下应该是没有GAP锁的，所以就解释不通了

**Comment by aneasystone** [comment]
@rocky-luo 非也，RC 级别下一样存在 GAP 锁，譬如这里 INSERT 时对 unique key 的唯一性校验就是一个特例。实际上这里写的不准确，唯一性校验时进行当前读，加的是 Next-Key 锁（LOCK_REC + LOCK_GAP）。

**Comment by broucetrong** [comment]
@aneasystone 请问一下大佬，第二步中描述【此时事务二和事务三成功获取记录上的 S 锁（LOCK_GAP | LOCK_REC | LOCK_S）】，这里的当前读应该是按唯一索引未命中的逻辑加的锁吧，【记录上】三个字令我有点疑惑
