### ISSUE TITLE
案例15的疑问

### ISSUE THREAD

**Issue by fennecs** [aneasystone/mysql-deadlocks#15]
"事务二再插入 a=9 这条记录，需要获取插入意向锁（lock_mode X locks gap before rec insert intention）和事务一持有的 Next-key 锁冲突"，这个时候事务一不是在等待Next-key 锁吗，为什么事务二会和还没有持有的锁冲突

**Comment by aneasystone** [comment]
MySQL 的加锁是按顺序的，先来后到

**Comment by fennecs** [comment]
好吧，感觉还要去看看锁队列的知识
