### ISSUE TITLE
一个死锁问题的请教

### ISSUE THREAD

**Issue by chishenqi** [aneasystone/mysql-deadlocks#16]
老师您好，打扰你了 之前自己业务场景发生了如下的死锁问题 但是我看了您的文章之后还是有点解释不通我的case，可能自己理解好有点问题。
RR模式下
CREATE TABLE `t` (
`id` int(11) NOT NULL,
`c` int(11) DEFAULT NULL,
`d` int(11) DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `c` (`c`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into t values(0,0,0),(5,5,5),(10,10,10),(15,15,15),(20,20,20),(25,25,25);

执行顺序
session 1
insert t values (9,9,9)[获取IX]
session 2
update t set d=9 where c=9 [给session1 上X锁，同时自己需要获取next-key,间隙锁获取成功，但是X锁获取失败进入锁等待]
session 1
update t set d=9 where c=9[需要获取next-key,间隙锁之间不冲突，间隙锁获取成功，但是X锁获取失败进入锁等待]
报发生死锁 session2回滚
疑问
明明session已经有X锁了 为什么session1的 update还会等待X锁造成死锁

死锁日志中也显示 session1 已经拥有X锁(lock_mode x locks but not gap)
但是等待next-key(lock_mode X) 间隙锁+X锁
这点很奇怪 因为自己的理解中间隙锁之间是不冲突的 间隙锁和插入意向锁是冲突的，此时session1已经拥有了 X锁 然后间隙锁也能获得 为什么死锁日志显示获取不到next-key

**Comment by chishenqi** [comment]
您好 不好意思打错了 update条件是索引C  update t set d=9 where c=9   c为非主键索引
session 1
insert t values (9,9,9)[获取IX]
session 2
update t set d=9 where c=9 [给session1 上X锁，同时自己需要获取next-key,间隙锁获取成功，但是X锁获取失败进入锁等待]
session 1
update t set d=9 where c=9[需要获取next-key,间隙锁之间不冲突，间隙锁获取成功，但是X锁获取失败进入锁等待]
报发生死锁 session2回滚
疑问
明明session已经有X锁了 为什么session1的 update还会等待X锁造成死锁

**Comment by aneasystone** [comment]
insert 时加的X锁是记录锁（lock_mode X locks but not gap），而 update 时加的X锁是next-key锁，这是两个锁，所以会等待。

**Comment by chishenqi** [comment]
> insert 时加的X锁是记录锁（lock_mode X locks but not gap），而 update 时加的X锁是next-key锁，这是两个锁，所以会等待。

我原先也是这样理解的 但后来看了一些文章 觉得next-key是两个锁可以存在 获取到间隙锁 然后等待排它锁的情况 session2已经是获得了间隙锁,但是无法获得排它锁。所以做了如下实验 
session 1
insert t values (9,9,9)[获取IX]
session 2
update t set d=9 where c=9 [给session1 上X锁，同时自己需要获取next-key,间隙锁获取成功，但是X锁获取失败进入锁等待]
session 1
insert t values (8,8,8)[session1 被间隙锁给session2的锁住了 说明session2已经上间隙锁了 ]
报发生死锁 session2回滚

因此针对之前提问你的场景 就觉得奇怪 session2的update 是获取间隙锁等待排它锁
                                            然后session1的update 应该是间隙锁没冲突能获得 然后排它锁的话 session1的事务因为insert也已经获得了 讲道理session1 的update获取next-key 应该没问题的

**Comment by aneasystone** [comment]
我觉得你可能是混淆了锁模式（lock modes）和锁类型（lock types）的概念。
共享锁 or 排他锁 都是锁模式，而表锁和行锁是锁类型，行锁又可以细分成记录锁、NextKey 锁等等，MySQL 中的一个锁是锁模式和锁类型的结合，不是独立存在的。

> 给session1 上X锁，同时自己需要获取next-key,间隙锁获取成功，但是X锁获取失败进入锁等待

所以你上面的这种说法就是有问题的。

**Comment by chishenqi** [comment]
感谢！！！ 一下子清晰了 等于 Mysql的锁是 
锁模式|锁类型的结合   RR模式下 先会走锁模式的冲突矩阵  如果都是行锁的话 就会接着判断锁类型是否可以兼容
这个case 中session1 的insert之后是获得lock X | not gap 
                   session2 的update  是获得lock X | gap 成功  但是lock X | next-key失败加入请求队列
                   session1  的update的话 接着想获得lock X | next-key  但是要等待session2
