### ISSUE TITLE
死锁代码检测

### ISSUE THREAD

**Issue by yscia007** [aneasystone/mysql-deadlocks#2]
想请教个问题，死锁代码是否有一些共同特征，能否通过静态代码检查发现这些问题，或者给出提示信息

**Comment by aneasystone** [comment]
@yscia007 你的想法很好，不过实现难度很大。首先得事先知道表结构，以及表中有哪些数据，因为不同的表结构和数据加锁方式是不一样的。然后需要通过代码静扫找到所有可能的事务，分析哪些事务会并发执行，哪些事务不会并发执行，这个工作量也是巨大的。但是只知道这些信息还是没办法判断是否会出现死锁的，还要分析出每个事务中可能执行的 SQL，不同的代码流程，不同的参数，得到的 SQL 也会不一样，这个组合起来是爆炸式的。
