### ISSUE TITLE
关于案例 14 重现步骤的疑问

### ISSUE THREAD

**Issue by yupnano** [aneasystone/mysql-deadlocks#6]
关于案例 14 的重现步骤，为啥两个 session 都先执行一个 delete 语句呢？

如果有 delete 的话，session1 会对在`uniq_kid_aid_biz_rid`索引上对 kdt_id 区间 (10，20] 加锁，session2 删除 ktd_id= 18，也会对区间 (10，20] 加锁，所以会等待 session1 完成，不会出现死锁。

我遇到的类似的死锁日志完全是由 insert 语句造成的。

### 案例14 重现步骤

| Session 1 | Session 2 |
| --- | --- |
|delete from t4 where kdt_id = 15 and admin_id = 1 and biz = 'retail' and role_id = '1';||
||delete from t4 where kdt_id = 18 and admin_id = 2 and biz = 'retail' and role_id = '1';|
||insert into t4(kdt_id, admin_id, biz, role_id, shop_id, operator, operator_id, create_time, update_time) VALUES('18', '2', 'retail', '2', '0', '0', '0', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);|
|INSERT INTO t4(kdt_id, admin_id, biz, role_id, shop_id, operator, operator_id, create_time, update_time) VALUES ('15', '1', 'retail', '2', '0', '0', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);|.|

**Comment by aneasystone** [comment]
> session1 会对在uniq_kid_aid_biz_rid索引上对 kdt_id 区间 (10，20] 加锁，session2 删除 ktd_id= 18，也会对区间 (10，20] 加锁

这个说法是不对的，session1 的 delete 语句条件是 `kdt_id = 15 and admin_id = 1 and biz = 'retail' and role_id = '1'`，很显然会走 `uniq_kid_aid_biz_rid` 这个索引，查询表里的记录，索引未命中，所以加的是 Gap 锁，同样的，session2 加的也是 Gap 锁，Gap 锁是不冲突的。
